### PR TITLE
Implement tag_category icons.

### LINKED ISSUE #49: Add icons to tag categories
To differentiate tags when they're included in a list, icons can be used as a shorthand for the tag's category.

### PR DESCRIPTION
**Pull request by mcglincy**
Fixes #49

SVG URLs and license info:

category
https://www.svgrepo.com/svg/17906/star
CC0

compendium
https://www.svgrepo.com/svg/327653/book
MIT

creator
https://www.svgrepo.com/svg/138116/skull
CC0

gamejam
CC0
https://www.svgrepo.com/svg/177226/spades-game

officialness
https://www.svgrepo.com/svg/89949/medal
CC0

https://www.svgrepo.com/page/licensing

### CODE REVIEW

**Comment by mcglincy** [comment]
I'll fix whatever is making CI unhappy.

**Comment by jdbann** [comment]
@mcglincy I realise a lot has changed since you opened this :/ How are you feeling about tag icons with the new tag format?

**Comment by mcglincy** [comment]
They seem less useful given the entry reorganization. Maybe leave out for
now?

**Comment by jdbann** [comment]
> They seem less useful given the entry reorganization. Maybe leave out for now?

Cool - I'll close for the time being but we have the branch to return to in future 👍

**Pull request closed without merging**
